"""
Bloomberg MARS XMarket curve catalog.

Each entry maps a curve profile name to its currency, Bloomberg curve ID
(``S{number}`` format) and a human-readable description.

Source: Bloomberg MARS XMarket curve list (as of 2026-03).
"""

from __future__ import annotations

from typing import TypedDict


class CurveEntry(TypedDict):
    profile: str        # e.g. "COP.OIS"
    currency: str       # e.g. "COP"
    curve_id: str       # e.g. "S329"
    description: str    # e.g. "Colombian Peso Overnight Swap (OIS)"


CURVES_CATALOG: list[CurveEntry] = [
    {"profile": "AED.12m",                  "currency": "AED", "curve_id": "S336", "description": "UAE Dirham Swap vs 12m"},
    {"profile": "AED.1m",                   "currency": "AED", "curve_id": "S334", "description": "UAE Dirham Swap vs 1m"},
    {"profile": "AED.3m",                   "currency": "AED", "curve_id": "S230", "description": "UAE Dirham Swap vs 3m"},
    {"profile": "AED.6m",                   "currency": "AED", "curve_id": "S335", "description": "UAE Dirham Swap vs 6m"},
    {"profile": "AED.Basis.3m.USD.3m",      "currency": "AED", "curve_id": "S231", "description": "AED 3m vs USD 3m Basis Swap"},
    {"profile": "ARS.3m",                   "currency": "ARS", "curve_id": "S216", "description": "Argentine Peso Swap vs 3m"},
    {"profile": "AUD.1m",                   "currency": "AUD", "curve_id": "S306", "description": "Australia Dollar Swap vs 1m"},
    {"profile": "AUD.3m",                   "currency": "AUD", "curve_id": "S303", "description": "Australia Dollar Swap vs 3m"},
    {"profile": "AUD.6m",                   "currency": "AUD", "curve_id": "S302", "description": "Australia Dollar Swap vs 6m"},
    {"profile": "AUD.6m.3m6m",              "currency": "AUD", "curve_id": "S1",   "description": "Australia Dollar Swap (3m/6m)"},
    {"profile": "AUD.6m.BankBills",         "currency": "AUD", "curve_id": "S148", "description": "Australia Bank Bills Curve"},
    {"profile": "AUD.Basis.3m.EUR.3m",      "currency": "AUD", "curve_id": "S291", "description": "AUD 3m vs EUR 3m Basis Swap"},
    {"profile": "AUD.Basis.3m.USD.3m",      "currency": "AUD", "curve_id": "S95",  "description": "AUD 3m vs USD 3m Basis Swap"},
    {"profile": "AUD.Fixing.6m",            "currency": "AUD", "curve_id": "S272", "description": "AUD CDSW Fixing Swap"},
    {"profile": "AUD.Fixing.6m.ISDA",       "currency": "AUD", "curve_id": "S268", "description": "AUD ISDA Fixing Swap"},
    {"profile": "AUD.OIS",                  "currency": "AUD", "curve_id": "S159", "description": "Australian Dollar Overnight Swap (OIS)"},
    {"profile": "BGN.3m",                   "currency": "BGN", "curve_id": "S183", "description": "Bulgarian Lev Swap vs 3m"},
    {"profile": "BHD.3m",                   "currency": "BHD", "curve_id": "S316", "description": "Bahrain Dinar Swap vs 3m"},
    {"profile": "BRL.BM&F Pre x DI",        "currency": "BRL", "curve_id": "S89",  "description": "BM&F Pre x DI"},
    {"profile": "BRL.CDI.Disc",             "currency": "BRL", "curve_id": "S304", "description": "Brazilian Real CDI Discount"},
    {"profile": "BRL.Offsh. Pre x DI",      "currency": "BRL", "curve_id": "S388", "description": "Offsh. Pre x DI"},
    {"profile": "CAD.1m",                   "currency": "CAD", "curve_id": "S330", "description": "Canada Dollar Swap vs 1m"},
    {"profile": "CAD.3m",                   "currency": "CAD", "curve_id": "S4",   "description": "Canada Dollar Swap vs 3m"},
    {"profile": "CAD.Basis.3m.EUR.3m",      "currency": "CAD", "curve_id": "S292", "description": "CAD 3m vs EUR 3m Basis Swap"},
    {"profile": "CAD.Basis.3m.USD.3m",      "currency": "CAD", "curve_id": "S135", "description": "CAD 3m vs USD 3m Basis Swap"},
    {"profile": "CAD.Fixing.3m",            "currency": "CAD", "curve_id": "S257", "description": "CAD CDSW Fixing Swap"},
    {"profile": "CAD.Fixing.3m.ISDA",       "currency": "CAD", "curve_id": "S263", "description": "CAD ISDA Fixing Swap"},
    {"profile": "CAD.OIS",                  "currency": "CAD", "curve_id": "S147", "description": "Canadian Dollar Overnight Swap (OIS)"},
    {"profile": "CHF.1m",                   "currency": "CHF", "curve_id": "S340", "description": "Swiss Franc Swap vs 1m"},
    {"profile": "CHF.3m",                   "currency": "CHF", "curve_id": "S254", "description": "Swiss Franc Swap vs 3m"},
    {"profile": "CHF.6m",                   "currency": "CHF", "curve_id": "S21",  "description": "Swiss Franc Swap vs 6m"},
    {"profile": "CHF.Basis.3m.EUR.3m",      "currency": "CHF", "curve_id": "S293", "description": "CHF 3m vs EUR 3m Basis Swap"},
    {"profile": "CHF.Basis.3m.USD.3m",      "currency": "CHF", "curve_id": "S93",  "description": "CHF 3m vs USD 3m Basis Swap"},
    {"profile": "CHF.Fixing.6m",            "currency": "CHF", "curve_id": "S259", "description": "CHF CDSW Fixing Swap"},
    {"profile": "CHF.Fixing.6m.ISDA",       "currency": "CHF", "curve_id": "S265", "description": "CHF ISDA Fixing Swap"},
    {"profile": "CHF.OIS",                  "currency": "CHF", "curve_id": "S234", "description": "Swiss Franc Overnight Swap (OIS)"},
    {"profile": "CLF.CCS.6m",               "currency": "CLF", "curve_id": "S379", "description": "CLF (vs. USD 6M)"},
    {"profile": "CLP.6m",                   "currency": "CLP", "curve_id": "S193", "description": "CLP Fixed x Camara Swap"},
    {"profile": "CLP.Basis.6m.USD.6m",      "currency": "CLP", "curve_id": "S194", "description": "CLP 6m vs USD 6m Basis Swap"},
    {"profile": "CLP.CCS.6m",               "currency": "CLP", "curve_id": "S521", "description": "CLP (vs USD 6M)"},
    {"profile": "CLP.OIS.Disc",             "currency": "CLP", "curve_id": "S423", "description": "Chilean Peso OIS Discount"},
    {"profile": "CNH.3m.IRS",               "currency": "CNH", "curve_id": "S368", "description": "CNH IRS 3M Curve"},
    {"profile": "CNH.Basis.3m.USD.3m",      "currency": "CNH", "curve_id": "S369", "description": "CNH vs. USD Basis"},
    {"profile": "CNH.CCS.3m",               "currency": "CNH", "curve_id": "S326", "description": "CNH/USD CCS Onshore Curve"},
    {"profile": "CNY.12m",                  "currency": "CNY", "curve_id": "S182", "description": "CNY Onshore Annual"},
    {"profile": "CNY.12m.depo",             "currency": "CNY", "curve_id": "S60",  "description": "CNY Onshore vs 1y PBOC Depo"},
    {"profile": "CNY.3m",                   "currency": "CNY", "curve_id": "S181", "description": "CNY Onshore Quarterly"},
    {"profile": "CNY.3m.Shibor",            "currency": "CNY", "curve_id": "S200", "description": "CNY Onshore vs 3m Shibor"},
    {"profile": "CNY.Basis.3m.USD.3m",      "currency": "CNY", "curve_id": "S149", "description": "CNY 3m vs USD 3m Basis Swap"},
    {"profile": "CNY.CCS.3m",               "currency": "CNY", "curve_id": "S328", "description": "CNY/USD CCS Onshore Curve"},
    {"profile": "CNY.CCS.6M",               "currency": "CNY", "curve_id": "S61",  "description": "CNY/USD NDF CCS Swap"},
    {"profile": "CNY.NDIRS.12m",            "currency": "CNY", "curve_id": "S362", "description": "CNY NDIRS Annual Swap"},
    {"profile": "CNY.NDIRS.3m",             "currency": "CNY", "curve_id": "S204", "description": "CNY NDIRS Quarterly Swap"},
    {"profile": "CNY.OIS",                  "currency": "CNY", "curve_id": "S228", "description": "CNY Overnight Swap (OIS)"},
    {"profile": "CNY.Onsh.USD.Depo",        "currency": "CNY", "curve_id": "S478", "description": "Onsh. CNY USD Deposit"},
    {"profile": "CNY.3M.5Y.LPR",            "currency": "CNY", "curve_id": "S525", "description": "CNY LPR 5y quarterly curve"},
    {"profile": "CNY.3M.1Y.LPR",            "currency": "CNY", "curve_id": "S523", "description": "CNY LPR 1y quarterly curve"},
    {"profile": "CNY.12M.5Y.LPR",           "currency": "CNY", "curve_id": "S526", "description": "CNY LPR 5y annual curve"},
    {"profile": "CNY.12M.1Y.LPR",           "currency": "CNY", "curve_id": "S524", "description": "CNY LPR 1y annual curve"},
    {"profile": "COP.3m",                   "currency": "COP", "curve_id": "S190", "description": "Colombian Peso vs 3m DTF"},
    {"profile": "COP.Basis.3m.USD.3m",      "currency": "COP", "curve_id": "S192", "description": "COP 3m vs USD 3m Basis Swap"},
    {"profile": "COP.NDCCS.3m",             "currency": "COP", "curve_id": "S191", "description": "COP/USD CCS Non-Deliverable Swap"},
    {"profile": "COP.OIS",                  "currency": "COP", "curve_id": "S329", "description": "Colombian Peso Overnight Swap (OIS)"},
    {"profile": "COP.OIS.Disc",             "currency": "COP", "curve_id": "S438", "description": "Colombian Peso OIS Discount"},
    {"profile": "CZK.3m",                   "currency": "CZK", "curve_id": "S319", "description": "Czech Koruna Swap vs 3m"},
    {"profile": "CZK.6m",                   "currency": "CZK", "curve_id": "S320", "description": "Czech Koruna Swap vs 6m"},
    {"profile": "CZK.6m.3mFRA",             "currency": "CZK", "curve_id": "S37",  "description": "Czech Koruna Swap vs 6m (3mFRA)"},
    {"profile": "CZK.Basis.3m.EUR.3m",      "currency": "CZK", "curve_id": "S296", "description": "CZK 3m vs EUR 3m Basis Swap"},
    {"profile": "CZK.Basis.3m.USD.3m",      "currency": "CZK", "curve_id": "S138", "description": "CZK 3m vs USD 3m Basis Swap"},
    {"profile": "DKK.1m",                   "currency": "DKK", "curve_id": "S337", "description": "Danish Krone Swap vs 1m"},
    {"profile": "DKK.3m",                   "currency": "DKK", "curve_id": "S338", "description": "Danish Krone Swap vs 3m"},
    {"profile": "DKK.6m",                   "currency": "DKK", "curve_id": "S5",   "description": "Danish Krone Swap vs 6m"},
    {"profile": "DKK.6m.6mFra",             "currency": "DKK", "curve_id": "S339", "description": "Danish Krone Swap vs 6m"},
    {"profile": "DKK.Basis.3m.EUR.3m",      "currency": "DKK", "curve_id": "S294", "description": "DKK 3m vs EUR 3m Basis Swap"},
    {"profile": "DKK.BASIS.3M.USD.3M",      "currency": "DKK", "curve_id": "S94",  "description": "DKK 3m vs USD 3m Basis Swap"},
    {"profile": "DKK.OIS",                  "currency": "DKK", "curve_id": "S186", "description": "Danish Krone Overnight Swap (OIS)"},
    {"profile": "EUR.12m",                  "currency": "EUR", "curve_id": "S314", "description": "Euro Swap vs 12m"},
    {"profile": "EUR.1m",                   "currency": "EUR", "curve_id": "S232", "description": "Euro Swap vs 1m"},
    {"profile": "EUR.3m",                   "currency": "EUR", "curve_id": "S201", "description": "Euro Swap vs 3m"},
    {"profile": "EUR.6m",                   "currency": "EUR", "curve_id": "S45",  "description": "EUR Swap vs 6m"},
    {"profile": "EUR.Basis.3m.USD.3m",      "currency": "EUR", "curve_id": "S92",  "description": "EUR 3m vs USD 3m Basis Curve"},
    {"profile": "EUR.Fixing.6m",            "currency": "EUR", "curve_id": "S169", "description": "EUR CDSW Fixing Swap"},
    {"profile": "EUR.Fixing.6m.ISDA",       "currency": "EUR", "curve_id": "S261", "description": "EUR ISDA Fixing Swap"},
    {"profile": "EUR.OIS",                  "currency": "EUR", "curve_id": "S133", "description": "Euro Overnight Swap (OIS)"},
    {"profile": "EUR.OIS.ESTR",             "currency": "EUR", "curve_id": "S514", "description": "Euro Overnight Swap (OIS) ESTR"},
    {"profile": "EUR.OIS.ESTR.Disc",        "currency": "EUR", "curve_id": "S403", "description": "Euro OIS ESTR Discount"},
    {"profile": "GBP.12m",                  "currency": "GBP", "curve_id": "S315", "description": "British Pound Swap vs 12m"},
    {"profile": "GBP.1m",                   "currency": "GBP", "curve_id": "S223", "description": "British Pound Swap vs 1m"},
    {"profile": "GBP.3m",                   "currency": "GBP", "curve_id": "S222", "description": "British Pound Swap vs 3m"},
    {"profile": "GBP.6m",                   "currency": "GBP", "curve_id": "S22",  "description": "British Pound Swap vs 6m"},
    {"profile": "GBP.Basis.3m.EUR.3m",      "currency": "GBP", "curve_id": "S290", "description": "GBP 3m vs EUR 3m Basis Swap"},
    {"profile": "GBP.Basis.3M.USD.3m",      "currency": "GBP", "curve_id": "S91",  "description": "GBP 3m vs USD 3m Basis Swap"},
    {"profile": "GBP.Fixing.6m",            "currency": "GBP", "curve_id": "S258", "description": "GBP CDSW Fixing Swap"},
    {"profile": "GBP.Fixing.6m.ISDA",       "currency": "GBP", "curve_id": "S264", "description": "GBP ISDA Fixing Swap"},
    {"profile": "GBP.OIS",                  "currency": "GBP", "curve_id": "S141", "description": "British Pound Overnight Swap (OIS)"},
    {"profile": "HKD.1m",                   "currency": "HKD", "curve_id": "S310", "description": "Hong Kong Dollar Swap vs 1m"},
    {"profile": "HKD.3m",                   "currency": "HKD", "curve_id": "S10",  "description": "Hong Kong Dollar Swap vs 3m"},
    {"profile": "HKD.6m",                   "currency": "HKD", "curve_id": "S311", "description": "Hong Kong Dollar Swap vs 6m"},
    {"profile": "HKD.Basis.3m.USD.3m",      "currency": "HKD", "curve_id": "S96",  "description": "HKD 3m vs USD 3m Basis Swap"},
    {"profile": "HKD.Fixing.3m",            "currency": "HKD", "curve_id": "S274", "description": "HKD CDSW Fixing Swap"},
    {"profile": "HKD.Fixing.3m.ISDA",       "currency": "HKD", "curve_id": "S270", "description": "HKD ISDA Fixing Swap"},
    {"profile": "HKD.OIS",                  "currency": "HKD", "curve_id": "S145", "description": "Hong Kong Dollar Overnight Swap (OIS)"},
    {"profile": "HUF.3m",                   "currency": "HUF", "curve_id": "S324", "description": "Hungarian Forint Swap vs 3m"},
    {"profile": "HUF.6m",                   "currency": "HUF", "curve_id": "S325", "description": "Hungarian Forint Swap vs 6m"},
    {"profile": "HUF.6m.3mFRA",             "currency": "HUF", "curve_id": "S124", "description": "Hungarian Forint Swap vs 6m (3mFRA)"},
    {"profile": "HUF.Basis.3m.EUR.3m",      "currency": "HUF", "curve_id": "S298", "description": "HUF 3m vs EUR 3m Basis Swap"},
    {"profile": "HUF.Basis.6m.USD.3m",      "currency": "HUF", "curve_id": "S140", "description": "HUF 6m vs USD 3m Basis Swap"},
    {"profile": "IDR.1m",                   "currency": "IDR", "curve_id": "S229", "description": "Indonesian Rupiah Onshore vs 1m TD (SBI)"},
    {"profile": "IDR.1m.Jibor",             "currency": "IDR", "curve_id": "S381", "description": "Indonesian Rupiah vs 1m JIBOR"},
    {"profile": "IDR.3m",                   "currency": "IDR", "curve_id": "S236", "description": "Indonesian Rupiah Onshore vs 3m TD (SBI)"},
    {"profile": "IDR.3m.Jibor",             "currency": "IDR", "curve_id": "S380", "description": "Indonesian Rupiah vs 3m JIBOR"},
    {"profile": "IDR.6m",                   "currency": "IDR", "curve_id": "S38",  "description": "Indonesian Rupiah Onshore vs IDR Fix"},
    {"profile": "IDR.Basis.3m.USD.3m",      "currency": "IDR", "curve_id": "S227", "description": "IDR vs. USD Basis"},
    {"profile": "IDR.CCS.6m",               "currency": "IDR", "curve_id": "S233", "description": "IDR/USD Onshore CCS Swap"},
    {"profile": "IDR.CCS.6m.ND",            "currency": "IDR", "curve_id": "S212", "description": "IDR/USD NDF CCS Swap"},
    {"profile": "IDR.OIS",                  "currency": "IDR", "curve_id": "S158", "description": "Indonesian Rupiah Overnight Swap (OIS)"},
    {"profile": "ILS.3m",                   "currency": "ILS", "curve_id": "S162", "description": "Israeli Shekel Swap vs 3m"},
    {"profile": "ILS.Basis.3m.USD.3m",      "currency": "ILS", "curve_id": "S163", "description": "ILS 3m vs USD 3m Basis Swap"},
    {"profile": "INR.6m.Mifor",             "currency": "INR", "curve_id": "S127", "description": "India Rupee MIFOR"},
    {"profile": "INR.CCS.6m",               "currency": "INR", "curve_id": "S68",  "description": "INR/USD Onshore CCS Swap"},
    {"profile": "INR.CCS.6m.ND",            "currency": "INR", "curve_id": "S69",  "description": "INR/USD NDF CCS Swap"},
    {"profile": "INR.NDIRS.OIS",            "currency": "INR", "curve_id": "S266", "description": "INR ND OIS Swap"},
    {"profile": "INR.OIS",                  "currency": "INR", "curve_id": "S46",  "description": "Onshore INR/INR OIS IRS Curve"},
    {"profile": "ISK.3m",                   "currency": "ISK", "curve_id": "S188", "description": "Icelandic Kronur Swap vs 3m"},
    {"profile": "ISK.Basis.3m.USD.3m",      "currency": "ISK", "curve_id": "S189", "description": "ISK 3m vs USD 3m Basis Swap"},
    {"profile": "JPY.1m",                   "currency": "JPY", "curve_id": "S307", "description": "Japanese Yen Swap vs 1m"},
    {"profile": "JPY.1M.Tibor.Domestic",    "currency": "JPY", "curve_id": "S396", "description": "JPY vs. 1M DTIBOR"},
    {"profile": "JPY.1M.Tibor.Euroyen",     "currency": "JPY", "curve_id": "S395", "description": "JPY vs. 1M ZTIBOR"},
    {"profile": "JPY.3m",                   "currency": "JPY", "curve_id": "S308", "description": "Japanese Yen Swap vs 3m"},
    {"profile": "JPY.3M.Tibor.Domestic",    "currency": "JPY", "curve_id": "S373", "description": "JPY 3M DOMESTIC TIBOR"},
    {"profile": "JPY.3M.Tibor.Euroyen",     "currency": "JPY", "curve_id": "S371", "description": "JPY 3M EUROYEN TIBOR"},
    {"profile": "JPY.6m",                   "currency": "JPY", "curve_id": "S13",  "description": "Japanese Yen Swap vs 6m"},
    {"profile": "JPY.6m.Tibor",             "currency": "JPY", "curve_id": "S187", "description": "Japanese Yen Swap vs 6m TIBOR"},
    {"profile": "JPY.6M.Tibor.Domestic",    "currency": "JPY", "curve_id": "S372", "description": "JPY 6M DOMESTIC TIBOR"},
    {"profile": "JPY.Basis.3m.EUR.3m",      "currency": "JPY", "curve_id": "S299", "description": "JPY 3m vs EUR 3m Basis Swap"},
    {"profile": "JPY.Basis.3m.USD.3m",      "currency": "JPY", "curve_id": "S97",  "description": "JPY 3m vs USD 3m Basis Swap"},
    {"profile": "JPY.Fixing.6m",            "currency": "JPY", "curve_id": "S262", "description": "JPY CDSW Fixing Swap"},
    {"profile": "JPY.Fixing.6m.ISDA",       "currency": "JPY", "curve_id": "S170", "description": "JPY ISDA Fixing Swap"},
    {"profile": "JPY.OIS",                  "currency": "JPY", "curve_id": "S195", "description": "Japanese Yen Overnight Swap (OIS)"},
    {"profile": "KRW.3m",                   "currency": "KRW", "curve_id": "S57",  "description": "South Korean Won Onshore Swap vs 3m"},
    {"profile": "KRW.Basis.3m.USD.6m",      "currency": "KRW", "curve_id": "S154", "description": "KRW 3m vs USD 6m Basis Swap"},
    {"profile": "KRW.CCS.6m",               "currency": "KRW", "curve_id": "S58",  "description": "KRW/USD Onshore CCS Swap"},
    {"profile": "KRW.CCS.6m.ND",            "currency": "KRW", "curve_id": "S59",  "description": "KRW/USD NDF CCS Swap"},
    {"profile": "KRW.NDIRS.3m",             "currency": "KRW", "curve_id": "S205", "description": "KRW/KRW ND Swap"},
    {"profile": "KWD.3m",                   "currency": "KWD", "curve_id": "S255", "description": "Kuwaiti Dinar Swap vs 3m"},
    {"profile": "KZT.3m",                   "currency": "KZT", "curve_id": "S175", "description": "Kazakhstan Tenge Swap vs 3m"},
    {"profile": "MXN.1m",                   "currency": "MXN", "curve_id": "S83",  "description": "Mexican Peso Swap vs 1m"},
    {"profile": "MXN.Basis.1m.USD.1m",      "currency": "MXN", "curve_id": "S151", "description": "MXN 1m vs USD 1m Basis Swap"},
    {"profile": "MXN.OIS",                  "currency": "MXN", "curve_id": "S364", "description": "Mexican OIS"},
    {"profile": "MXN.OIS.Disc",             "currency": "MXN", "curve_id": "S428", "description": "Mexican Peso OIS Discount"},
    {"profile": "MXN.OIS.TIIE",             "currency": "MXN", "curve_id": "S583", "description": "Mexican OIS (TIIE 28d)"},
    {"profile": "MYR.3m",                   "currency": "MYR", "curve_id": "S39",  "description": "Malaysian Ringgit Onshore Swap vs 3m"},
    {"profile": "MYR.Basis.3m.USD.3m",      "currency": "MYR", "curve_id": "S150", "description": "MYR 3m vs USD 3m Basis Swap"},
    {"profile": "MYR.CCS.6m",               "currency": "MYR", "curve_id": "S78",  "description": "MYR/USD Onshore CCS Swap"},
    {"profile": "MYR.CCS.6m.ND",            "currency": "MYR", "curve_id": "S208", "description": "MYR/USD NDF CCS Swap"},
    {"profile": "MYR.NDIRS.3m",             "currency": "MYR", "curve_id": "S209", "description": "MYR/MYR ND Swap"},
    {"profile": "MYR.OIS",                  "currency": "MYR", "curve_id": "S267", "description": "Onshore MYR/MYR OIS Swap Curve"},
    {"profile": "NOK.1m",                   "currency": "NOK", "curve_id": "S350", "description": "Norwegian Krone Swap vs 1m"},
    {"profile": "NOK.3m",                   "currency": "NOK", "curve_id": "S312", "description": "Norwegian Krone Swap vs 3m"},
    {"profile": "NOK.6m",                   "currency": "NOK", "curve_id": "S313", "description": "Norwegian Krone Swap vs 6m"},
    {"profile": "NOK.6m.IMMFRA",            "currency": "NOK", "curve_id": "S16",  "description": "Norwegian Krone Swap vs 6m (IMM FRA)"},
    {"profile": "NOK.Basis.3m.EUR.3m",      "currency": "NOK", "curve_id": "S297", "description": "NOK 3m vs EUR 3m Basis Swap"},
    {"profile": "NOK.Basis.3m.USD.3m",      "currency": "NOK", "curve_id": "S134", "description": "NOK 3m vs USD 3m Basis Swap"},
    {"profile": "NOK.OIS",                  "currency": "NOK", "curve_id": "S487", "description": "NOK OIS"},
    {"profile": "NZD.3m",                   "currency": "NZD", "curve_id": "S15",  "description": "New Zealand Dollar Swap vs 3m"},
    {"profile": "NZD.Basis.3m.USD.3m",      "currency": "NZD", "curve_id": "S136", "description": "NZD 3m vs USD 3m Basis Swap"},
    {"profile": "NZD.Fixing.3m",            "currency": "NZD", "curve_id": "S273", "description": "NZD CDSW Fixing Swap"},
    {"profile": "NZD.Fixing.3m.ISDA",       "currency": "NZD", "curve_id": "S269", "description": "NZD ISDA Fixing Swap"},
    {"profile": "NZD.OIS",                  "currency": "NZD", "curve_id": "S198", "description": "New Zealand Dollar Overnight Swap (OIS)"},
    {"profile": "PHP.3m",                   "currency": "PHP", "curve_id": "S81",  "description": "Philippine Peso Onshore Swap vs 3m"},
    {"profile": "PHP.CCS.6m",               "currency": "PHP", "curve_id": "S65",  "description": "PHP/USD Onshore CCS Swap"},
    {"profile": "PHP.CCS.6m.ND",            "currency": "PHP", "curve_id": "S66",  "description": "PHP/USD NDF CCS Swap"},
    {"profile": "PHP.NDIRS.3m",             "currency": "PHP", "curve_id": "S207", "description": "PHP/PHP ND Swap"},
    {"profile": "PKR.6m",                   "currency": "PKR", "curve_id": "S160", "description": "Pakistani Rupee Swap vs 6m"},
    {"profile": "PKR.Basis.6m.USD.6m",      "currency": "PKR", "curve_id": "S161", "description": "PKR 6m vs USD 6m Basis Swap"},
    {"profile": "PEN.OIS",                  "currency": "PEN", "curve_id": "S374", "description": "Peruvian Sol Overnight Swap (OIS)"},
    {"profile": "PLN.1m.Wibor",             "currency": "PLN", "curve_id": "S378", "description": "PLN vs. 1M WIBOR"},
    {"profile": "PLN.3m",                   "currency": "PLN", "curve_id": "S322", "description": "Polish Zloty Swap vs 3m"},
    {"profile": "PLN.6m",                   "currency": "PLN", "curve_id": "S323", "description": "Polish Zloty Swap vs 6m"},
    {"profile": "PLN.6m.3mFRA",             "currency": "PLN", "curve_id": "S48",  "description": "Polish Zloty Swap vs 6m (3m FRA)"},
    {"profile": "PLN.Basis.3m.EUR.3m",      "currency": "PLN", "curve_id": "S321", "description": "PLN 3m vs EUR 3m Basis Swap"},
    {"profile": "PLN.Basis.3m.USD.3m",      "currency": "PLN", "curve_id": "S139", "description": "PLN 3m vs USD 3m Basis Swap"},
    {"profile": "PLN.OIS",                  "currency": "PLN", "curve_id": "S327", "description": "Polish Zloty Overnight Swap (OIS)"},
    {"profile": "RON.3m",                   "currency": "RON", "curve_id": "S225", "description": "RON (vs. 3M ROBOR)"},
    {"profile": "RON.3m.EUR",               "currency": "RON", "curve_id": "S363", "description": "RON (vs. EUR 3M)"},
    {"profile": "RON.Basis.3m.EUR.3m",      "currency": "RON", "curve_id": "S301", "description": "RON 3m vs EUR 3m Basis Swap"},
    {"profile": "RUB.3m",                   "currency": "RUB", "curve_id": "S179", "description": "Russian Ruble Swap vs 3m"},
    {"profile": "RUB.Basis.3m.USD.3m",      "currency": "RUB", "curve_id": "S180", "description": "RUB 3m vs USD 3m Basis Swap"},
    {"profile": "RUB.CCS.3m",               "currency": "RUB", "curve_id": "S237", "description": "RUB/USD CCS Swap vs 3m USD Libor"},
    {"profile": "RUB.FIXING.7d",            "currency": "RUB", "curve_id": "S513", "description": "RUB (vs. 7D KEY RATE)"},
    {"profile": "RUB.OIS",                  "currency": "RUB", "curve_id": "S356", "description": "Russian Ruble Overnight Swap (OIS)"},
    {"profile": "SAR.12m",                  "currency": "SAR", "curve_id": "S333", "description": "Saudi Riyal Swap vs 12m"},
    {"profile": "SAR.1m",                   "currency": "SAR", "curve_id": "S331", "description": "Saudi Riyal Swap vs 1m"},
    {"profile": "SAR.3m",                   "currency": "SAR", "curve_id": "S166", "description": "Saudi Riyal Swap vs 3m"},
    {"profile": "SAR.6m",                   "currency": "SAR", "curve_id": "S332", "description": "Saudi Riyal Swap vs 6m"},
    {"profile": "SEK.1m",                   "currency": "SEK", "curve_id": "S347", "description": "Swedish Krona Swap vs 1m"},
    {"profile": "SEK.3m",                   "currency": "SEK", "curve_id": "S20",  "description": "Swedish Krona Swap vs 3m"},
    {"profile": "SEK.6m",                   "currency": "SEK", "curve_id": "S348", "description": "Swedish Krona Swap vs 6m"},
    {"profile": "SEK.Basis.3m.EUR.3m",      "currency": "SEK", "curve_id": "S295", "description": "SEK 3m vs EUR 3m Basis Swap"},
    {"profile": "SEK.Basis.3m.USD.3m",      "currency": "SEK", "curve_id": "S137", "description": "SEK 3m vs USD 3m Basis Swap"},
    {"profile": "SEK.OIS",                  "currency": "SEK", "curve_id": "S185", "description": "Swedish Krone Overnight Swap (OIS)"},
    {"profile": "SGD.1m",                   "currency": "SGD", "curve_id": "S341", "description": "Singapore Dollar Onshore Swap vs 1m"},
    {"profile": "SGD.3m",                   "currency": "SGD", "curve_id": "S342", "description": "Singapore Dollar Onshore Swap vs 3m"},
    {"profile": "SGD.6m",                   "currency": "SGD", "curve_id": "S44",  "description": "Singapore Dollar Onshore Swap vs 6m"},
    {"profile": "SGD.6m.Offshore",          "currency": "SGD", "curve_id": "S72",  "description": "Singapore Dollar Offshore Swap vs 6m"},
    {"profile": "SGD.Basis.6m.USD.6m",      "currency": "SGD", "curve_id": "S98",  "description": "SGD 6m vs USD 6m Basis Swap"},
    {"profile": "SGD.CCS.6m",               "currency": "SGD", "curve_id": "S71",  "description": "SGD/USD Onshore CCS Curve"},
    {"profile": "SGD.CCS.6m.Offshore",      "currency": "SGD", "curve_id": "S73",  "description": "SGD/USD Offshore CCS Curve"},
    {"profile": "SGD.Fixing.6m",            "currency": "SGD", "curve_id": "S275", "description": "SGD CDSW Fixing Swap"},
    {"profile": "SGD.Fixing.6m.ISDA",       "currency": "SGD", "curve_id": "S271", "description": "SGD ISDA Fixing Swap"},
    {"profile": "SGD.OIS.SORA",             "currency": "SGD", "curve_id": "S527", "description": "SGD OIS SORA"},
    {"profile": "THB.3m.BIBOR",             "currency": "THB", "curve_id": "S40",  "description": "Thai Baht Onshore Swap vs 3m (BIBOR)"},
    {"profile": "THB.6m",                   "currency": "THB", "curve_id": "S172", "description": "Thai Baht Swap vs 6m"},
    {"profile": "THB.6m.Fixvsbibor",        "currency": "THB", "curve_id": "S345", "description": "Thai Baht Swap vs 6m BIBOR"},
    {"profile": "THB.6m.Fixvsrepo",         "currency": "THB", "curve_id": "S343", "description": "Thai Baht Swap vs 6m Fixed Repo"},
    {"profile": "THB.Basis.6m.USD.6m",      "currency": "THB", "curve_id": "S156", "description": "THB 6m vs USD 6m Basis Swap"},
    {"profile": "THB.CCS.6m",               "currency": "THB", "curve_id": "S53",  "description": "THB/USD Onshore CCS Curve"},
    {"profile": "THB.CCS.6m.ND",            "currency": "THB", "curve_id": "S210", "description": "THB/USD NDF CSS Swap"},
    {"profile": "THB.NDIRS.6m.ND",          "currency": "THB", "curve_id": "S211", "description": "THB/THB ND Swap"},
    {"profile": "THB.OIS",                  "currency": "THB", "curve_id": "S146", "description": "Thailand Baht Overnight Swap (OIS)"},
    {"profile": "TRY.3m",                   "currency": "TRY", "curve_id": "S164", "description": "Turkish Lira Swap vs 3m"},
    {"profile": "TRY.Basis.3m.USD.6m",      "currency": "TRY", "curve_id": "S165", "description": "TRY 3m vs USD 3m Basis Swap"},
    {"profile": "TRY.CCS.3m",               "currency": "TRY", "curve_id": "S235", "description": "TRY/USD CCS Swap vs 3m USD Libor"},
    {"profile": "TRY.OIS",                  "currency": "TRY", "curve_id": "S522", "description": "TRY OIS curve"},
    {"profile": "TWD.3m",                   "currency": "TWD", "curve_id": "S41",  "description": "Taiwan Dollar Swap vs 3m"},
    {"profile": "TWD.3m.Taibor",            "currency": "TWD", "curve_id": "S386", "description": "Onshore TWD TAIBOR IRS"},
    {"profile": "TWD.Basis.3m.USD.3m",      "currency": "TWD", "curve_id": "S155", "description": "TWD 3m vs USD 3m Basis Swap"},
    {"profile": "TWD.CCS.3m",               "currency": "TWD", "curve_id": "S55",  "description": "TWD/USD Onshore CCS Swap"},
    {"profile": "TWD.CCS.6m.ND",            "currency": "TWD", "curve_id": "S56",  "description": "TWD/USD NDF CSS Swap"},
    {"profile": "TWD.NDIRS.3m",             "currency": "TWD", "curve_id": "S203", "description": "TWD/TWD ND Swap"},
    {"profile": "USD.12m",                  "currency": "USD", "curve_id": "S349", "description": "US Dollar Swap vs 12m"},
    {"profile": "USD.3m",                   "currency": "USD", "curve_id": "S23",  "description": "US Dollar Swap vs 3m"},
    {"profile": "USD.3m.Annual",            "currency": "USD", "curve_id": "S47",  "description": "US Dollar Swap (Act/360)"},
    {"profile": "USD.3m.Quarterly",         "currency": "USD", "curve_id": "S171", "description": "US Dollar Swap (Quarterly)"},
    {"profile": "USD.Basis.3m.1m",          "currency": "USD", "curve_id": "S50",  "description": "USD 3M Libor vs USD 1M Libor Basis Swap"},
    {"profile": "USD.Basis.3m.6m",          "currency": "USD", "curve_id": "S51",  "description": "USD 3M Libor vs USD 6M Libor Basis Swap"},
    {"profile": "USD.Basis.CP",             "currency": "USD", "curve_id": "S87",  "description": "CP Spreads Swap"},
    {"profile": "USD.Basis.FedFunds",       "currency": "USD", "curve_id": "S85",  "description": "US Fed Funds Spreads Swap"},
    {"profile": "USD.Basis.Prime",          "currency": "USD", "curve_id": "S86",  "description": "US Prime Spreads Swap"},
    {"profile": "USD.Basis.Tbill",          "currency": "USD", "curve_id": "S52",  "description": "US T-Bill Spreads Swap"},
    {"profile": "USD.Fixing.3m",            "currency": "USD", "curve_id": "S168", "description": "USD CDSW Fixing Swap"},
    {"profile": "USD.Fixing.3m.ISDA",       "currency": "USD", "curve_id": "S260", "description": "USD ISDA Fixing Swap"},
    {"profile": "USD.Muni",                 "currency": "USD", "curve_id": "S357", "description": "US Dollar Muni Swap (%Libor vs BMA Muni)"},
    {"profile": "USD.Muni.Swaps",           "currency": "USD", "curve_id": "S43",  "description": "US Dollar Muni Swap"},
    {"profile": "USD.OIS",                  "currency": "USD", "curve_id": "S42",  "description": "US Dollar Overnight Swap (OIS)"},
    {"profile": "USD.SOFR",                 "currency": "USD", "curve_id": "S490", "description": "US Dollar SOFR (vs Fixed)"},
    {"profile": "USD.SOFR.Disc",            "currency": "USD", "curve_id": "S400", "description": "US Dollar SOFR Discount (CSA)"},
    {"profile": "VND.3m",                   "currency": "VND", "curve_id": "S196", "description": "Vietnam Dong Swap vs 3m"},
    {"profile": "VND.CCS.6m.ND",            "currency": "VND", "curve_id": "S214", "description": "VND/USD NDF CSS Swap"},
    {"profile": "ZAR.3m",                   "currency": "ZAR", "curve_id": "S18",  "description": "South African Rand Swap vs 3m"},
    {"profile": "ZAR.Basis.3m.EUR.3m",      "currency": "ZAR", "curve_id": "S300", "description": "ZAR 3m vs EUR 3m Basis Swap"},
    {"profile": "ZAR.Basis.3m.USD.3m",      "currency": "ZAR", "curve_id": "S99",  "description": "ZAR 3m vs USD 3m Basis Swap"},
    {"profile": "ZAR.FIXING.DEPO.JIBAR",    "currency": "ZAR", "curve_id": "S519", "description": "South Africa JIBAR Linked Deposit Curve"},
    {"profile": "ZAR.FIXING.DEPO",          "currency": "ZAR", "curve_id": "S477", "description": "South Africa Deposit Curve"},
]

# label → curve_id mapping for Streamlit selectbox
CURVES_BY_LABEL: dict[str, str] = {
    f"{e['profile']} ({e['currency']})": e["curve_id"]
    for e in CURVES_CATALOG
}

# curve_id → label reverse mapping (for display)
CURVES_BY_ID: dict[str, str] = {v: k for k, v in CURVES_BY_LABEL.items()}
